{
 "title": "TCPMetrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Zero Window Metrics",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "zerowindow_metric{job=\"tcp-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Metrics",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "irate(duration_metric{job=\"tcp-exporter\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCPRetransmission",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(retransmission_metric{job=\"tcp-exporter\"}[5m])",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "TcpWindowSizeUpdate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "rate(window_scale_metric{job=\"tcp-exporter\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WindowScaleMetrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "rate(window_scale_metric{job=\"tcp-exporter\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RST Metrics",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rst_metric{job=\"tcp-expoter\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}