name: BuildPipeline

on:
  push:
    branches:
      - "build-pipeline"
      - "master"

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: GatherCommitSHA
          run: |
            export IMAGE_TAG=$(git rev-parse --short HEAD)
            echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
  docker:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REPO_OWNER }}
          password: ${{ secrets.REPO_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          file: docker/Dockerfile
          push: true
          tags: |
            emirozbir/tcp-exporter:latest
            emirozbir/tcp-exporter:${{needs.init.outputs.IMAGE_TAG}}
          