name: BuildPipeline

on:
  push:
    branches:
      - "pre-release"
      - "master"
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GatherCommitSHA
        id: init
        run: |
          export IMAGE_TAG=$(git rev-parse --short HEAD)

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

    outputs:
      image_tag: ${{ steps.init.outputs.IMAGE_TAG }}

  docker:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REPO_OWNER }}
          password: ${{ secrets.REPO_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          file: docker/Dockerfile
          push: true
          tags: |
            emirozbir/tcp-exporter:latest
            emirozbir/tcp-exporter:${{needs.init.outputs.image_tag}}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: emirozbir/tcp-exporter:latest
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'